### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by TechnologyClassroom** [benyanke/internet_noise_bash#1]
Your script is cool!

You should add a license.md files so that others have the freedom to reuse and give back to your project.

I would suggest a GPL or MIT license.  You can find examples of this throughout my github.

**Comment by benyanke** [comment]
I ended up not continuing on this due to my heavy load. However, I will add a GPL, and happily take PRs if someone wants to continue with it

**Comment by benyanke** [comment]
Added with commit id 17e6d38
